use_frameworks!

platform :ios, '8.0'

target 'BYCCategory_Example' do
  pod 'BYCCategory', :path => '../'

  target 'BYCCategory_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
